sonar.projectKey=Bahmni_bahmni-module-fhir2-addl-extension
sonar.organization=bahmni
sonar.projectName=bahmni-module-fhir2-addl-extension

sonar.sources=api/src/main/java,omod/src/main/java
sonar.tests=api/src/test/java,omod/src/test/java
sonar.java.binaries=api/target/classes,omod/target/classes
sonar.java.test.binaries=api/target/test-classes,omod/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=api/target/jacoco-reports/jacoco.xml

sonar.sourceEncoding=UTF-8
